### ISSUE TITLE
Issue finding cutoff.txt, so manually entered  ... is this right? 

### ISSUE THREAD

**Issue by taylorshab** [fenderglass/quake#1]
Hello, 

After entering this code: 
`$ python /u/home/a/arvin/bin/Quake/bin/cov_model.py --int counts.txt`

I received the error message: 

```
Traceback (most recent call last):
  File "/u/home/a/arvin/bin/Quake/bin/cov_model.py", line 251, in <module>
    main()
File "/u/home/a/arvin/bin/Quake/bin/cov_model.py", line 33, in main
    print 'Cutoff: %s' % open('cutoff.txt').readline().rstrip()
IOError: [Errno 2] No such file or directory: 'cutoff.txt'
```

After manually creating a cutoff.txt file, setting it equal to 200, the program responded:
`Cutoff: 200`

Is it proper to manually create this file? If not, how should I handle this error message? 

Thanks.

**Comment by fenderglass** [comment]
This is not an official Quake repository, please refer to http://www.cbcb.umd.edu/software/quake/
